"""empty message

Revision ID: 032534d8b66f
Revises: 834538ed337a
Create Date: 2017-08-09 15:15:12.672000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032534d8b66f'
down_revision = '834538ed337a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('product_sku', sa.String(length=255), nullable=True))
    op.drop_column('order', 'product_price')
    op.drop_column('order', 'product_name')
    op.drop_column('order', 'product_quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('product_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('product_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('product_price', sa.NUMERIC(precision=2, scale=0), autoincrement=False, nullable=True))
    op.drop_column('order', 'product_sku')
    # ### end Alembic commands ###
