"""empty message

Revision ID: 2cd68922ebd5
Revises: e3d707e9a730
Create Date: 2017-07-28 18:23:13.005000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd68922ebd5'
down_revision = 'e3d707e9a730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Numeric(precision=8), nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
