"""empty message

Revision ID: 4f167944bb2a
Revises: e62e7ef9c814
Create Date: 2017-08-15 13:39:29.708000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f167944bb2a'
down_revision = 'e62e7ef9c814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_number')
    # ### end Alembic commands ###
