"""empty message

Revision ID: 521fef883626
Revises: efcf64e320e3
Create Date: 2017-08-01 23:38:55.275000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521fef883626'
down_revision = 'efcf64e320e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_filename', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('shop_user', 'image_url')
    op.drop_column('shop_user', 'image_filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_user', sa.Column('image_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shop_user', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'image_filename')
    # ### end Alembic commands ###
