"""empty message

Revision ID: c03c25258411
Revises: 
Create Date: 2017-07-27 13:03:23.997000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03c25258411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(length=30), nullable=True))
    op.add_column('products', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('sell_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sell_price')
    op.drop_column('products', 'price')
    op.drop_column('products', 'description')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
