"""empty message

Revision ID: ddf0e6d2a2f3
Revises: 521fef883626
Create Date: 2017-08-03 11:49:48.648000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf0e6d2a2f3'
down_revision = '521fef883626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount', sa.Integer(), nullable=True))
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'discount')
    # ### end Alembic commands ###
