"""empty message

Revision ID: e3d707e9a730
Revises: c03c25258411
Create Date: 2017-07-27 15:22:00.127000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d707e9a730'
down_revision = 'c03c25258411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
