"""empty message

Revision ID: e62e7ef9c814
Revises: fe4ef7714707
Create Date: 2017-08-14 15:03:09.912000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62e7ef9c814'
down_revision = 'fe4ef7714707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'ship_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('ship_price', sa.NUMERIC(precision=2, scale=0), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
